name: Build & Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: Build TestTube Plugin v1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: download Grind and setup
        run: |
          wget -O grind https://github.com/AnharHussainMiah/grind/releases/download/v0.6.1-alpha/grind-x86_64-unknown-linux-musl
          chmod +x grind
          sudo mv grind /usr/local/bin/

      - name: Download all dependencies
        run: grind install

      - name: Compile plugin and bundle it
        run: |
          echo "==> clean any old TestTube Directory"
          rm -rf TestTube/
          echo "==> creating TestTube Directory"
          mkdir TestTube
          echo "==> copying libs over"
          cp -r libs TestTube/
          echo "==> building jar"
          grind build
          echo "==> debug show current state"
          ls -l
          echo "==> copying jar over"
          cp build/TestTube.jar TestTube/
          echo "==> generating bundle checksum.."
          grind integrity generate TestTube/
          echo "==> removing any old zip files"
          rm -rf TestTube.zip
          echo "==> creating new zip bundle..."
          zip -r TestTube.zip TestTube/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TestTube Plugin
          path: TestTube.zip

  release:
    needs: build
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: TestTube Plugin
          path: TestTube.zip

      - name: Display downloaded files
        run: ls -lh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: TestTube.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
